language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-webapp-config' ]; then cd .. && eval "mv $currentfolder generator-webapp-config" && cd generator-webapp-config; fi

